//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Events')
export class EventsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('date', { nullable: true })
  date: Date;

  @Column('text', { nullable: true })
  description: string;

  @Column('text', { nullable: true })
  status: string;
}
