//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { EventsEntity } from './db/Events.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [SettingsEntity, EventsEntity];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Events: [
        {
          title: 'title 1',
          date: '2023-08-24T15:53:40.345Z',
          description: 'description 1',
          status: 'status 1',
          id: 81,
        },
        {
          title: 'title 2',
          date: '2023-09-11T15:22:01.148Z',
          description: 'description 2',
          status: 'status 2',
          id: 74,
        },
        {
          title: 'title 3',
          date: '2023-12-02T03:47:42.058Z',
          description: 'description 3',
          status: 'status 3',
          id: 25,
        },
        {
          title: 'title 4',
          date: '2024-09-28T09:43:35.537Z',
          description: 'description 4',
          status: 'status 4',
          id: 80,
        },
        {
          title: 'title 5',
          date: '2024-03-20T17:34:08.556Z',
          description: 'description 5',
          status: 'status 5',
          id: 93,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('EventsEntity', data.Events);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
