//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="design like this website horizontally scrollable event time line with additional feature it be with respect to months event passed from the current month will be dimmed by color active event color be green upcoming be yellow" />
    <CardContent>
      design like this website horizontally scrollable event time line with
      additional feature it be with respect to months event passed from the
      current month will be dimmed by color active event color be green upcoming
      be yellow
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
