//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Events: [
      {
        title: 'title 1',
        date: '2023-08-24T15:53:40.345Z',
        description: 'description 1',
        status: 'status 1',
        id: 81,
      },
      {
        title: 'title 2',
        date: '2023-09-11T15:22:01.148Z',
        description: 'description 2',
        status: 'status 2',
        id: 74,
      },
      {
        title: 'title 3',
        date: '2023-12-02T03:47:42.058Z',
        description: 'description 3',
        status: 'status 3',
        id: 25,
      },
      {
        title: 'title 4',
        date: '2024-09-28T09:43:35.537Z',
        description: 'description 4',
        status: 'status 4',
        id: 80,
      },
      {
        title: 'title 5',
        date: '2024-03-20T17:34:08.556Z',
        description: 'description 5',
        status: 'status 5',
        id: 93,
      },
    ],
  },
};
export default data;
