//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Events: {
      name: 'Events',
      fields: {
        title: 'Title',
        date: 'Date',
        description: 'Description',
        status: 'Status',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Events: {
      name: 'Events (fr)',
      fields: {
        title: 'Title (fr)',
        date: 'Date (fr)',
        description: 'Description (fr)',
        status: 'Status (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
